version: "3"

volumes:
    redis_vol:
    mysql_vol:
    zoo_vol:
    kafka_vol:
    hb_vol:
    hadoop_namenode:
    hadoop_datanode:
    hadoop_historyserver:
    hbase_data:
    hbase_zookeeper_data:
    prometheus_data:

networks:
    total:
        driver: bridge

services:
    es:
        image: elasticsearch:7.13.1
        container_name: es
        networks:
            - total
        environment:
            - TZ=Asia/Shanghai
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - http.port=9200
        privileged: true
        ports:
            - "9200:9200"
        restart: always

    otel-collector:
        image: otel/opentelemetry-collector-contrib-dev:latest
        command: [ "--config=/etc/otel-collector-config.yml", "${OTELCOL_ARGS}" ]
        volumes:
            - ./otel-collector-config.yml:/etc/otel-collector-config.yml
        ports:
            - "1888:1888"   # pprof extension
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "4317:4317"   # OTLP gRPC receiver
            - "55670:55679" # zpages extension
        depends_on:
            - jaeger-all-in-one

    jaeger-all-in-one:
        platform: linux/x86_64
        image: rancher/jaegertracing-all-in-one:1.20.0
        container_name: jaeger
        networks:
            - total
        environment:
            - TZ=Asia/Shanghai
            - SPAN_STORAGE_TYPE=elasticsearch
            - ES_SERVER_URLS=http://es:9200
            - LOG_LEVEL=debug
            # - JAEGER_SAMPLER_MANAGER_HOST_PORT:jaeger:5778
        depends_on:
            - es
        privileged: true
        ports:
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "4318:4318"
            - "14250:14250"
            - "14268:14268"
            - "14269:14269"
            - "9411:9411"
        restart: always

    victoriametrics:
        container_name: victoriametrics
        image: victoriametrics/victoria-metrics
        ports:
            - "8428:8428"
            - "8089:8089"
            - "8089:8089/udp"
            - "2003:2003"
            - "2003:2003/udp"
            - "4242:4242"
        command:
            - '--storageDataPath=/storage'
            - '--graphiteListenAddr=:2003'
            - '--opentsdbListenAddr=:4242'
            - '--httpListenAddr=:8428'
            - '--influxListenAddr=:8089'
        restart: always

    grafana:
        image: grafana/grafana:latest
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - "3000:3000"