Global:
  Source: "config(local)"
  ChangeMe: "v1"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "47.115.230.248"
  Port: 2379

Server:
  Name: "DoutokFavoriteServer"
  Address: "127.0.0.1"
  Port: 8085

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1"

Snowflake:
  Node: 602

MySQL:
  Host: "127.0.0.1"
  Port: 8091
  User: "tiktok"
  Password: "password"
  Database: "Tiktok"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"

Redis:
  Dest: "127.0.0.1:6379"
  Password: ""
  FavCache:
    Num: 3
  FavCntCache:
    Num: 4
