name: build latest

on:
  pull_request:
    branches: ["main"]

env:
  REGISTRY: registry.cn-shanghai.aliyuncs.com

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build docker image
        run:
          docker version
          
          docker login --username=${{ secrets.ALIYUN_KEY_ID }} --password=${{ secrets.ALIYUN_KEY_SECRET }} registry.cn-shanghai.aliyuncs.com
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/api:latest --build-arg target=api
          
          docker push ${{ env.REGISTRY }}/doutok/api:latest
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/comment:latest --build-arg target=comment
          
          docker push ${{ env.REGISTRY }}/doutok/comment:latest
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/favorite:latest --build-arg target=favorite
          
          docker push ${{ env.REGISTRY }}/doutok/favorite:latest
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/feed:latest --build-arg target=feed
          
          docker push ${{ env.REGISTRY }}/doutok/feed:latest
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/message:latest --build-arg target=message
          
          docker push ${{ env.REGISTRY }}/doutok/message:latest
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/publsih:latest --build-arg target=publsih
          
          docker push ${{ env.REGISTRY }}/doutok/publsih:latest
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/api:latest --build-arg target=relation
          
          docker push ${{ env.REGISTRY }}/doutok/api:latest
          
          docker build . --tag ${{ env.REGISTRY }}/doutok/user:latest --build-arg target=user
          
          docker push ${{ env.REGISTRY }}/doutok/user:latest
        
